server.port=8082

spring.application.name=product-service

spring.datasource.url=jdbc:mysql://localhost:3306/noshop_product_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

product.image.default-url=/images/image-not-available.png

aws.region=ap-south-1
aws.s3.bucket=noshop-product-images
aws.cloudfront.domain=YOUR_CLOUDFRONT_DOMAIN

jwt.secret=your-very-long-secret-key-at-least-32-characters
jwt.expiration=86400000

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.kafka.bootstrap-servers=localhost:9092